/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#ffb4a1",
        "secondary": "#386753",
        "surface-container": "#f1eedb",
        "on-secondary-fixed-variant": "#1f4f3c",
        "on-tertiary-fixed": "#161a32",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#ffdbd2",
        "on-primary-fixed-variant": "#7c2e19",
        "surface-container-highest": "#e6e3d0",
        "inverse-primary": "#ffb4a1",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-variant": "#e6e3d0",
        "error-container": "#ffdad6",
        "outline": "#88726d",
        "secondary-fixed": "#bbeed4",
        "secondary-fixed-dim": "#9fd1b8",
        "on-surface-variant": "#55423e",
        "tertiary-fixed": "#dfe0ff",
        "outline-variant": "#dbc1ba",
        "on-secondary-fixed": "#002115",
        "surface-dim": "#dddbc8",
        "tertiary-fixed-dim": "#c2c4e5",
        "error": "#ba1a1a",
        "secondary-container": "#b8ebd1",
        "surface-tint": "#9a442d",
        "primary": "#9a442d",
        "on-error": "#ffffff",
        "surface-container-low": "#f7f4e1",
        "on-surface": "#1c1c11",
        "on-error-container": "#93000a",
        "on-secondary-container": "#3d6c57",
        "inverse-surface": "#313124",
        "background": "#fdfae7",
        "inverse-on-surface": "#f4f1de",
        "on-primary-container": "#5b1604",
        "on-tertiary-fixed-variant": "#424560",
        "tertiary-container": "#9294b3",
        "tertiary": "#5a5c79",
        "surface-bright": "#fdfae7",
        "surface": "#fdfae7",
        "surface-container-high": "#ece9d6",
        "on-tertiary-container": "#2a2d47",
        "on-background": "#1c1c11",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#3c0800",
        "primary-container": "#e07a5f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Epilogue", "Public Sans"],
        "body": ["Be Vietnam Pro", "Public Sans"],
        "label": ["Be Vietnam Pro", "Public Sans"],
        "sans": ["Public Sans", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
